apiVersion: apps/v1
kind: Deployment
metadata:
  name: karunya-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karunya-app
  template:
    metadata:
      labels:
        app: karunya-app
    spec:
      containers:
        - name: karunya-app
          image: karunya-online-learning:1   # Local Minikube image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          command: ["npm", "start"]          # Ensure the app starts correctly
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: karunya-service
spec:
  type: NodePort
  selector:
    app: karunya-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
