apiVersion: apps/v1
kind: Deployment
metadata:
  name: karunya-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karunya-app
  template:
    metadata:
      labels:
        app: karunya-app
    spec:
      containers:
      - name: karunya-app
        image: karunya-online-learning:1   # Local Minikube image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: karunya-service
spec:
  type: LoadBalancer    # ✅ Correct for Minikube tunnel
  selector:
    app: karunya-app
  ports:
  - protocol: TCP
    port: 3000          # ✅ External port
    targetPort: 3000    # ✅ Container port

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "yourpassword"
            - name: MYSQL_DATABASE
              value: "user_profiles"
          ports:
            - containerPort: 3306

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysql